<?php

define('QODE_NEWS_VERSION', '1.0.2');
define('QODE_NEWS_ABS_PATH', dirname(__FILE__));
define('QODE_NEWS_REL_PATH', dirname(plugin_basename(__FILE__ )));
define('QODE_NEWS_URL_PATH', plugin_dir_url( __FILE__ ));
define('QODE_NEWS_LIB_PATH', QODE_NEWS_ABS_PATH.'/lib');
define('QODE_NEWS_LIB_URL_PATH', QODE_NEWS_URL_PATH.'lib');
define('QODE_NEWS_ASSETS_PATH', QODE_NEWS_ABS_PATH.'/assets');
define('QODE_NEWS_ASSETS_URL_PATH', QODE_NEWS_URL_PATH.'assets');
define('QODE_NEWS_MODULES_PATH', QODE_NEWS_ABS_PATH.'/modules');
define('QODE_NEWS_MODULES_URL_PATH', QODE_NEWS_URL_PATH.'modules');
define('QODE_NEWS_BLOG_PATH', QODE_NEWS_MODULES_PATH.'/blog');
define('QODE_NEWS_BLOG_URL_PATH', QODE_NEWS_MODULES_URL_PATH.'/blog');
define('QODE_NEWS_LIKE_PATH', QODE_NEWS_MODULES_PATH.'/like');
define('QODE_NEWS_LIKE_URL_PATH', QODE_NEWS_MODULES_URL_PATH.'/like');
define('QODE_NEWS_SHORTCODES_PATH', QODE_NEWS_MODULES_PATH.'/shortcodes');
define('QODE_NEWS_SHORTCODES_URL_PATH', QODE_NEWS_MODULES_URL_PATH.'shortcodes');
define('QODE_NEWS_WIDGETS_PATH', QODE_NEWS_MODULES_PATH.'/widgets');
define('QODE_NEWS_WIDGETS_URL_PATH', QODE_NEWS_MODULES_URL_PATH.'widgets');
define('QODE_NEWS_REACTIONS_PATH', QODE_NEWS_MODULES_PATH.'/reactions');
define('QODE_NEWS_REACTIONS_URL_PATH', QODE_NEWS_MODULES_URL_PATH.'reactions');
define('QODE_NEWS_REVIEW_PATH', QODE_NEWS_MODULES_PATH.'/review');
define('QODE_NEWS_REVIEW_URL_PATH', QODE_NEWS_MODULES_URL_PATH.'review');